version: '3'
services:
  app:
    build: .
    environment:
      APP_ENV: "development"
    ports:
      - "6005:6005" # For development; SWANK port. cf. Dockerfile
      - "5000:5000"
    volumes:
      - ./:/app
      - cache:/root/.cache
      - slime_cache:/root/.slime
volumes:
  cache:
  slime_cache:
